---
mock_with: ':rspec'

appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.project:
  delete: true

.travis.yml:
  includes:
    - env: PUPPET_GEM_VERSION="~> 7.0" CHECK=parallel_spec
      rvm: 2.7.2
      stage: spec
